// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QabrWebApp.Dal.Entities;

#nullable disable

namespace QabrWebApp.Dal.Migrations
{
    [DbContext(typeof(QabrWebAppDatabaseContext))]
    [Migration("20260628000000_AddCanImportFlyerToUtilisateur")]
    partial class AddCanImportFlyerToUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QabrWebApp.Dal.Entities.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAbonnement")
                        .HasColumnType("datetime2");

                    b.Property<int>("MosqueeId")
                        .HasColumnType("int");

                    b.Property<bool>("NotifActive")
                        .HasColumnType("bit");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MosqueeId");

                    b.HasIndex("UtilisateurId", "MosqueeId")
                        .IsUnique();

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.Mosquee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DerniereSyncOsm")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OsmId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OsmId")
                        .IsUnique()
                        .HasFilter("[OsmId] IS NOT NULL");

                    b.ToTable("Mosquees");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.PriereJanaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnneeDeces")
                        .HasColumnType("int");

                    b.Property<int?>("AnneeNaissance")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHeurePriere")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstAnonyme")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MosqueeId")
                        .HasColumnType("int");

                    b.Property<string>("NomDefunt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaysEnterrement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("VilleEnterrement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MosqueeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("PrieresJanaza");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.RappelPush", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnvoyeAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MosqueeId")
                        .HasColumnType("int");

                    b.Property<int>("PriereJanazaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriereJanazaId");

                    b.HasIndex("DateEnvoi", "EnvoyeAt");

                    b.ToTable("RappelsPush");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseDomicile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("CanImportFlyer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExpoToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double?>("LatitudeDomicile")
                        .HasColumnType("float");

                    b.Property<double?>("LongitudeDomicile")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NotifMouvement")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RayonNotification")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.UtilisateurToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpoToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId", "ExpoToken")
                        .IsUnique();

                    b.ToTable("UtilisateurTokens");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.Abonnement", b =>
                {
                    b.HasOne("QabrWebApp.Dal.Entities.Mosquee", "Mosquee")
                        .WithMany("Abonnements")
                        .HasForeignKey("MosqueeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QabrWebApp.Dal.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Abonnements")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mosquee");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.PriereJanaza", b =>
                {
                    b.HasOne("QabrWebApp.Dal.Entities.Mosquee", "Mosquee")
                        .WithMany("PrieresJanaza")
                        .HasForeignKey("MosqueeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QabrWebApp.Dal.Entities.Utilisateur", "Utilisateur")
                        .WithMany("PrieresDeclarees")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mosquee");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.RappelPush", b =>
                {
                    b.HasOne("QabrWebApp.Dal.Entities.PriereJanaza", "PriereJanaza")
                        .WithMany()
                        .HasForeignKey("PriereJanazaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriereJanaza");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.UtilisateurToken", b =>
                {
                    b.HasOne("QabrWebApp.Dal.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.Mosquee", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("PrieresJanaza");
                });

            modelBuilder.Entity("QabrWebApp.Dal.Entities.Utilisateur", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("PrieresDeclarees");
                });
#pragma warning restore 612, 618
        }
    }
}
